#ifndef MIU_ERRORS
#define MIU_ERRORS

#define MIU_SUCCESS 0

#define MIU_FAILED_WRITE -001
#define MIU_WRITE_TIMEOUT -002
#define MIU_FAILED_READ -003
#define MIU_READ_TIMEOUT -004
#define MIU_SEND_BUFFER_FULL -005
#define MIU_RECV_BUFFER_FULL -006
#define MIU_INVALID_LEN -007

#define MIU_IPV4_WRONG_VERSION -101
#define MIU_IPV4_INVALID_HDR_SIZE -102
#define MIU_IPV4_INVALID_TOT_SIZE -103
#define MIU_IPV4_PACKET_EXPIRED -104
#define MIU_IPV4_INVALID_CHECKSUM -105
#define MIU_IPV4_MALFORMED_OPTIONS -106

#define MIU_IPV4_TOO_MANY_OPTIONS -107

#define MIU_TCP_INVALID_HDR_SIZE -201
#define MIU_TCP_INVALID_CHECKSUM -202
#define MIU_TCP_MALFORMED_OPTIONS -203

#define MIU_TCP_TOO_MANY_OPTIONS -204
#define MIU_TCP_INVALID_STATE_CHANGE -205

#define MIU_TCPIPV4_INVALID_TOT_SIZE -301

#endif
